<?php
// $Id$

//==========================================//
// SEARCH BLOCK
//==========================================//

/**
* Implementation of hook_block().
*/
function usersearch_block($op = 'list', $delta = '', $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks['usersearch-block'] = array(
        'info' => t('User search')
      );
      return $blocks;
    case 'view':
      switch ($delta) {
        case 'usersearch-block':
          $block['subject'] = t('User Search');
          $block['content'] = drupal_get_form('usersearch_form');
          break;
      }
      return $block;
  }
}

/**
* Implementation of hook_form
**/
function usersearch_form($form_state) {

  $path = drupal_get_path('module', 'usersearch');
  drupal_add_js($path.'/autoSuggest/jquery.autoSuggest.js', 'module');
  drupal_add_js($path.'/autosuggest-custom.js', 'module');
  drupal_add_css($path.'/autoSuggest/autoSuggest.css', 'module');
  drupal_add_css($path.'/usersearch.css', 'module');

  $form['search_string'] = array(
    '#type' => 'textfield',
    '#title' => t('Profile Search'), 
    '#size' => 30, 
    '#maxlength' => 64, 
    '#description' => t('Enter name or Company'),
    '#prefix' => '<div class="usersearch-field">',
    '#suffix' => '</div>',
  );
  
  $form['submit'] = array('#type' => 'submit', '#value' => t('Search'));
  return $form;
}

/**
* Implementation of hook_menu
**/
function usersearch_menu() {
  $items = array();
  $items['usersearch/autosuggest'] = array(
    'page callback' => 'usersearch_autosuggest',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );
  $items['usersearch/search'] = array(
    'page callback' => 'full_search',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
* Callback function for the search results page
**/
//~ function _user_search_results($testarg) {

  function full_search() {
  
  $output = '';
  $output = t('<div class="user-search">');
  $user_results;
  $company_results;
  $search_input = check_plain(arg(2));
  
  $result = db_query('SELECT uid FROM {users} WHERE UPPER(name) LIKE "%%%s%"', strtoupper($search_input));

  while ($row = db_fetch_object($result)) {
    $user_tmp = user_load($row->uid);
    if (!(in_array($row->uid, $user_results)) && in_array('company', array_values($user_tmp->roles)))
      $company_results[] = $row->uid;
    else {
      if (!(in_array($row->uid, $user_results)) && in_array('applicant', array_values($user_tmp->roles)))
        $user_results[] = $row->uid;
    }
  }
  
  $result = db_query('SELECT node.uid as uid 
                      FROM {node} node
                      INNER JOIN {content_type_uprofile} uprofile ON node.nid = uprofile.nid
                      WHERE UPPER(uprofile.field_name_value) LIKE "%%%s%"', strtoupper($search_input));
                      
  while ($row = db_fetch_object($result)) {
    $user_tmp = user_load($row->uid);
    if (!(in_array($row->uid, $user_results)) && in_array('applicant', array_values($user_tmp->roles)))
      $user_results[] = $row->uid;
  }
  
  /** ----- PRINT THE COMPANY AVATARS ------*/
  
  $output .= t('<h3>Companies</h3>');
  
  if (empty($company_results))
    $output .= t('No companies found to match your search criteria.');
  
  foreach ($company_results as $user_result) {
  
    $user_tmp = user_load($user_result);
    
    //Build the node to output
    $user_profile = get_user_profile($user_tmp->uid);
    
    $output .= node_view($user_profile, $teaser = true);
  
  } // foreach
  
  
  /** ----- PRINT THE USER AVATARS ------*/
  
  $output .= t('<h3>Users</h3>');
  
  if (empty($user_results))
    $output .= t('No users found to match your search criteria.');
  
  foreach ($user_results as $user_result) {
  
    $user_tmp = user_load($user_result);
    
    $user_profile = get_user_profile($user_tmp->uid);
    
    $output .= node_view($user_profile, $teaser = true);
  
  }
  return $output;
}

function usersearch_autosuggest() {
  $user_results;
  $company_results;
  $list = array();
  $arg = $_GET['as'];
  $list = _usersearch_get_contacts($arg);
  
  header("Content-type: application/json");
  echo json_encode($list);
  exit();
}

function usersearch_form_submit($form, &$form_state) {
  $search_string = $form['search_string']['#value'];
  $form_state['redirect'] = 'usersearch/search/'.trim($search_string);
}

function _usersearch_get_contacts($arg) {
  $list = array();
  global $user;
  $current_user = $user->uid;
  $relationship_status = '1';
  $list_size = 3;
    
  //~ Create array of contacts
  $result = db_query_range('SELECT realname.name AS name, users_user_relationships.uid AS uid, users_user_relationships.picture AS picture
                        FROM {user_relationships} user_relationships
                        LEFT JOIN {users} users_user_relationships ON user_relationships.requestee_id = users_user_relationships.uid
                        LEFT JOIN {users} users_user_relationships_1 ON user_relationships.requester_id = users_user_relationships_1.uid
                        LEFT JOIN {user_relationship_types} user_relationship_types_user_relationships ON user_relationships.rtid = user_relationship_types_user_relationships.rtid
                        INNER JOIN (SELECT node.uid AS uid, uprofile.field_name_value AS name FROM {node} node INNER JOIN {content_type_uprofile} uprofile ON node.nid = uprofile.nid WHERE LOWER(uprofile.field_name_value) like LOWER("%%%s%"))
                         realname ON realname.uid = users_user_relationships.uid
                        WHERE (user_relationships.approved = "%s") AND (user_relationships.requester_id = %d)
                        ORDER BY realname.name ASC', $arg, $relationship_status, $current_user, 0, 10);
  $user_results = array();
  while ($row = db_fetch_object($result)) {
  
    //~ Get the right avatar image to display, depending on whether or not the user has uploaded a custom profile avatar or not
    //~ $base_path = base_path();
    $image_path = $row->picture;

    if (!$row->picture) {
    
      $result = db_query('SELECT nid FROM {node} n WHERE type = \'%s\' AND n.uid = %d LIMIT %d', 'uprofile', $row->uid, 1);
      $result = db_fetch_object($result);
      $user_profile = node_load($result->nid);

      if ($user_profile->field_gender[0]['value'] == 'Male')
        $image_path = path_to_theme().'/images/default-image-m.jpg';
      elseif ($user_profile->field_gender[0]['value'] == 'Female')
        $image_path = path_to_theme().'/images/default-image-f.jpg';
      else
        $image_path = path_to_theme().'/images/default-image.jpg';
    }
  
      /* Now fill the auto complete menu... */
      $list[] = array('value' => $row->uid, 'name' => truncate_utf8($row->name, 50, TRUE, TRUE), 'image' => theme('imagecache', 'thumb-mini', $image_path, '', ''));
  }
  return $list;
}
