<?php
// $Id$

/**
* Implementation of hook_block().
*/
function usersearch_block($op = 'list', $delta = '', $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks['usersearch-block'] = array(
        'info' => t('User search')
      );
      return $blocks;
    case 'view':
      switch ($delta) {
        case 'usersearch-block':
          $block['subject'] = t('User Search');
          $block['content'] = drupal_get_form('usersearch_form');
          break;
      }
      return $block;
  }
}

/**
* Implementation of hook_menu
**/
function usersearch_menu() {
  $items = array();
  $items['usersearch/autosuggest.json'] = array(
    'page callback' => 'usersearch_autosuggest',
    'access callback' => '_profilewizard_access',
    'file' => 'usersearch_ajax.inc',
  );
  $items['usersearch/search/%'] = array(
		'title' => 'Search Results',
    'page callback' => '_user_search_results',
    'page arguments' => array(2),
    'access callback' => '_profilewizard_access',
    'file' => 'usersearch_search.inc',
  );
  return $items;
}

/**
 * Function to calculate access to menu
 *
 * @return boolean
 *  True if valid
 */
function _usersearch_access() {
  /*global $user;
  $node = node_load($nid);
  return $user && $user->uid &&
  (
    // The user is not blocked and logged in at least once.
    ($user->access && $user->status && ((user_access('use profile wizard') && $node->uid == $user->uid) || user_access('administer profile wizard')))
  );/**/
	return TRUE;
}

/**
* Implementation of hook_form
**/
function usersearch_form($form_state) {
  $path = drupal_get_path('module', 'usersearch');
  drupal_add_js($path.'/autoSuggest/jquery.autoSuggest.js', 'module');
  drupal_add_js($path.'/autosuggest-custom.js', 'module');
  drupal_add_css($path.'/autoSuggest/autoSuggest.css', 'module');
  drupal_add_css($path.'/usersearch.css', 'module');

  $form['search_string'] = array(
    '#type' => 'textfield',
    '#title' => t('Profile Search'), 
    '#size' => 30, 
    '#maxlength' => 64, 
    '#description' => t('Enter name or Company'),
    '#prefix' => '<div class="usersearch-field">',
    '#suffix' => '</div>',
  );
  
  $form['submit'] = array('#type' => 'submit', '#value' => t('Search'));
  return $form;
}

/**
 * Form submition handler
 */
function usersearch_form_submit($form, &$form_state) {
  $search_string = $form['search_string']['#value'];
  $form_state['redirect'] = 'usersearch/search/'.trim($search_string);
}

